### ISSUE TITLE
Giant Console Error

### ISSUE THREAD

**Issue by Fargus5** [LucasRomier/BetterMobAI#2]
Hello, there is a warn in the console, with the Giant.

`[16:35:54]: [WARN] [BetterMobAI] Task #3696 for BetterMobAI v3.0.1 alpha generated an exception
java.lang.IllegalArgumentException: data should be interface org.bukkit.block.data.BlockData got class org.bukkit.material.MaterialData
at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.spawnParticle(CraftWorld.java:2419) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.spawnParticle(CraftWorld.java:2414) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.spawnParticle(CraftWorld.java:2403) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.spawnParticle(CraftWorld.java:2383) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.spawnParticle(CraftWorld.java:2363) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.craftbukkit.v1_15_R1.CraftWorld.spawnParticle(CraftWorld.java:2358) ~[patched_1.15.2.jar:git-Paper-226]
at com.LucasRomier.BetterMobAI.Mobs.Entity.Bosses.BetterGiant.lambda$trackBoulder$0(BetterGiant.java:281) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:461) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1240) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1157) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946) ~[patched_1.15.2.jar:git-Paper-226]
at java.lang.Thread.run(Thread.java:834) [?:?]`

**Comment by LucasRomier** [comment]
Hi,

Thanks, this is not a crucial error, so it will be fixed with the next relase.
