### ISSUE TITLE
BetterMobAI v3.0.1 alpha generated an exception

### ISSUE THREAD

**Issue by Fargus5** [LucasRomier/BetterMobAI#4]
```
[20:57:24]: [WARN] [BetterMobAI] Task #3152772 for BetterMobAI v3.0.1 alpha generated an exception
java.lang.IllegalArgumentException: x not finite
at org.bukkit.util.NumberConversions.checkFinite(NumberConversions.java:118) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.Location.checkFinite(Location.java:1071) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.craftbukkit.v1_15_R1.entity.CraftEntity.teleport(CraftEntity.java:499) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.craftbukkit.v1_15_R1.entity.CraftLivingEntity.teleport(CraftLivingEntity.java:556) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.craftbukkit.v1_15_R1.entity.CraftEntity.teleport(CraftEntity.java:493) ~[patched_1.15.2.jar:git-Paper-226]
at com.LucasRomier.BetterMobAI.Mobs.Entity.Overworld.BetterEnderman$3.run(BetterEnderman.java:100) ~[?:?]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-226]
at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:461) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1240) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:430) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:1157) ~[patched_1.15.2.jar:git-Paper-226]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:946) ~[patched_1.15.2.jar:git-Paper-226]
at java.lang.Thread.run(Thread.java:834) [?:?]
```

Hello, there is always the same error

This is the latest version on spigot, problem has not been fixed, but you already closed the issue.

Thanks :-)

**Comment by Strovo** [comment]
same error for me

[20:44:38] [Server thread/WARN]: [BetterMobAI] Task #1669511 for BetterMobAI v3.0.1 alpha generated an exception
java.lang.IllegalArgumentException: x not finite
        at org.bukkit.util.NumberConversions.checkFinite(NumberConversions.java:118) ~[survival.jar:git-Spigot-2f5d615-d07a78b]
        at org.bukkit.Location.checkFinite(Location.java:616) ~[survival.jar:git-Spigot-2f5d615-d07a78b]
        at org.bukkit.craftbukkit.v1_15_R1.entity.CraftEntity.teleport(CraftEntity.java:461) ~[survival.jar:git-Spigot-2f5d615-d07a78b]
        at org.bukkit.craftbukkit.v1_15_R1.entity.CraftLivingEntity.teleport(CraftLivingEntity.java:494) ~[survival.jar:git-Spigot-2f5d615-d07a78b]
        at org.bukkit.craftbukkit.v1_15_R1.entity.CraftEntity.teleport(CraftEntity.java:455) ~[survival.jar:git-Spigot-2f5d615-d07a78b]
        at com.LucasRomier.BetterMobAI.Mobs.Entity.Overworld.BetterEnderman$3.run(BetterEnderman.java:100) ~[?:?]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:81) ~[survival.jar:git-Spigot-2f5d615-d07a78b]
        at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:400) [survival.jar:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.MinecraftServer.b(MinecraftServer.java:1036) [survival.jar:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.DedicatedServer.b(DedicatedServer.java:406) [survival.jar:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:984) [survival.jar:git-Spigot-2f5d615-d07a78b]
        at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:824) [survival.jar:git-Spigot-2f5d615-d07a78b]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]

Spigot 1.15.2

**Comment by Fargus5** [comment]
?

**Comment by OpticFusion1** [comment]
Make a new issue at https://github.com/OpticFusion1/BetterMobMechanics/issues (follow the format) please.
(Working on re-doing this plugin, having issues made there which follow a format is easier and better :P)

**Comment by Fargus5** [comment]
never get a fix about this
BetterMobMechanics doesn't not exist
